[package]
name = "hostname"
version = "0.1.0"
description = "Get hostname. Compatiable with windows and linux."
keywords = ["hostname", "objectid"]
authors = ["fengcen <fengcen.love@gmail.com>"]
repository = "https://github.com/fengcen/hostname.git"
homepage = "https://github.com/fengcen/hostname"
documentation = "https://docs.rs/hostname"
readme = "README.md"
license = "MIT"

[lib]
name = "hostname"
path = "src/lib.rs"

[features]
unstable = []

[target."cfg(unix)".dependencies]
libc = "^0.1"

[target."cfg(windows)".dependencies]
winutil = "^0.1"
