[package]
name = "hostname"
version = "0.1.5"
description = "Get hostname. Compatible with windows and linux, redox."
keywords = ["hostname"]
authors = ["fengcen <fengcen.love@gmail.com>"]
repository = "https://github.com/fengcen/hostname.git"
homepage = "https://github.com/fengcen/hostname"
documentation = "https://docs.rs/hostname"
readme = "README.md"
license = "MIT"

[lib]
name = "hostname"
path = "src/lib.rs"

[features]
unstable = []

[dependencies]
match_cfg = "^0.1"

[target.'cfg(any(unix, target_os = "redox"))'.dependencies]
libc = "^0.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "^0.3", features = ["sysinfoapi"] }
