[package]
name = "hostname"
version = "0.2.0"
description = "Cross-platform hostname functions"
categories = ["api-bindings", "os"]
keywords = ["hostname", "gethostname", "sethostname", "GetComputerNameExW"]
authors = [
    "fengcen <fengcen.love@gmail.com>",
    "svartalf <self@svartalf.info>"
]
repository = "https://github.com/fengcen/hostname.git"
readme = "README.md"
license = "MIT"

[lib]
name = "hostname"
path = "src/lib.rs"

[features]
unstable = []

[dependencies]
match_cfg = "^0.1"

[target.'cfg(any(unix, target_os = "redox"))'.dependencies]
libc = "^0.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "^0.3", features = ["sysinfoapi"] }

[dev-dependencies]
version-sync = "0.8"
